### ISSUE TITLE
Add Visual Studio 2015 support

### ISSUE THREAD

**Issue by hiredgunhouse** [seldary/Ersx.Net#3]
Please add support for VS2015.

**Comment by PavelKovalets** [comment]
Is there any chance that this awesome plugin will work for VS2015?

**Comment by hiredgunhouse** [comment]
Well actually now it makes sense to add support to VS2017 as well :)

**Comment by seldary** [comment]
I created this because there was no easy way to sort my resx files. After that, [resxmanager](https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager) added this feature, so there is not much value in this extension...

I suggest that you use resxmanager (supports vs2015 & vs2017), or if you insist, you can create a PR.
